JFLAGS = -g
JC = javac
OPT = -O3
#OPT = -g
WARN = -Wall


QuickSort: QuickSort.class
	java QuickSort

QuickSort.class: QuickSort.java
	$(JC) $(JFLAGS) QuickSort.java

clean:
	$(RM) QuickSort.class

clobber:
	$(RM) QuickSort.class


